name: CI

on: [push, pull_request]

jobs:
  paket:
    name: Paket test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: joseluisq/paket
          options: -v ${{ github.workspace }}:/gitnow
          shell: fish
          run: |
            fish -v
            paket --version
            git config --global --add safe.directory /gitnow
            paket add /gitnow
            /gitnow/testing/test.fish

  fisher:
    name: Fisher test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: joseluisq/paket
          options: -v ${{ github.workspace }}:/gitnow
          shell: fish
          run: |
            apk add curl && apk upgrade
            curl -sL git.io/fisher | source
            fish -v
            fisher --version
            fisher install /gitnow
            /gitnow/testing/test.fish
